blog/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.PostList.as_view(), name='home'),
    path('<slug:slug>/', views.post_detail, name='post_detail'),
    path(
        '<slug:slug>/edit_comment/<int:comment_id>',
        views.comment_edit, name='comment_edit'),
    path(
        '<slug:slug>/delete_comment/<int:comment_id>',
        views.comment_delete, name='comment_delete'),
]

codestar/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('about/', include('about.urls'), name='about-urls'),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('', include('blog.urls'), name='blog-urls'),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField

STATUS = ((0, "Draft"), (1, "Published"))


# Create your models here.
class Post(models.Model):
    """
    Stores a single blog post entry related to :model:`auth.User`.
    """
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="blog_posts"
    )
    featured_image = CloudinaryField('image', default='placeholder')
    content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)
    excerpt = models.TextField(blank=True)
    updated_on = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-created_on"]

    def __str__(self):
        return f"{self.title} | written by {self.author}"


class Comment(models.Model):
    """
    Stores a single comment entry related to :modl:`auth.User`
    and :model:`blog.Post`. 
    """
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, related_name="comments"
    )
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="commenter"
    )
    body = models.TextField(max_length=200)
    approved = models.BooleanField(default=False)
    created_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["created_on"]

    def __str__(self):
        return f"Comment {self.body} by {self.author}"

blog/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    """
    Form to leave a comment on the post that is stored the model of Comment.
    """
    class Meta:
        model = Comment
        fields = ('body',)

blog/views.py
from django.shortcuts import render, get_object_or_404, reverse
from django.views import generic
from django.contrib import messages
from django.http import HttpResponseRedirect
from .models import Post, Comment
from .forms import CommentForm


# Create your views here.
class PostList(generic.ListView):
    """
    Display the list of the post :model:`blog.Post`.
    **Template:**
    :template:`blog/index.html`
    """
    queryset = Post.objects.filter(status=1)
    template_name = "blog/index.html"
    paginate_by = 6


def post_detail(request, slug):
    """
    Display an individual post :model:`blog.Post`.

    **Context**

    ``post``
        An instance of :model:`blog.Post`.
    ``comments``
        All approved comments related to the post.
    ``comment_count``
        A count of approved comments related to the post.
    ``comment_form``
        An instance of :form:`blog.CommentForm`.
    **Template:**

    :template:`blog/post_detail.html`
    """
    queryset = Post.objects.filter(status=1)
    post = get_object_or_404(queryset, slug=slug)
    comments = post.comments.all().order_by("-created_on")
    comment_count = post.comments.filter(approved=True).count()

    if request.method == "POST":
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.author = request.user
            comment.post = post
            comment.save()
            messages.add_message(
                request, messages.SUCCESS,
                'Comment submitted and awaiting approval'
             )
    comment_form = CommentForm()
    return render(
        request,
        "blog/post_detail.html",
        {
            "post": post,
            "comments": comments,
            "comment_count": comment_count,
            "comment_form": comment_form,
        },
    )


def comment_edit(request, slug, comment_id):
    """
    Display an individual comment for edit.

    **Context**

    ``post``
        An instance of :model:`blog.Post`.
    ``commnet``
        A single comment related to the post.
    ``comment_form``
        An isntance of :form:`blog.CommentForm`.
    """
    if request.method == "POST":
        queryset = Post.objects.filter(status=1)
        post = get_object_or_404(queryset, slug=slug)
        comment = get_object_or_404(Comment, pk=comment_id)
        comment_form = CommentForm(data=request.POST, instance=comment)

        if comment_form.is_valid() and comment.author == request.user:
            comment = comment_form.save(commit=False)
            comment.post = post
            comment.approved = False
            comment.save()
            messages.add_message(request, messages.SUCCESS, 'Comment Updated!')
        else:
            messages.add_message(
                request, messages.ERROR, 'Error updating comment!')
    return HttpResponseRedirect(reverse('post_detail', args=[slug]))


def comment_delete(request, slug, comment_id):
    """
    Delete an individual comment.

    **Context**

    ``post``
        An instance of :model:`blog.Post`.
    ``comment``
        A single comment related to the post.
    """
    queryset = Post.objects.filter(status=1)
    post = get_object_or_404(queryset, slug=slug)
    comment = get_object_or_404(Comment, pk=comment_id)

    if comment.author == request.user:
        comment.delete()
        messages.add_message(request, messages.SUCCESS, 'Comment deleted!')
    else:
        messages.add_message(
            request, messages.ERROR, 'You can only delete your own comments!')

    return HttpResponseRedirect(reverse('post_detail', args=[slug]))

blog/templates/blog/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<!-- index.html content starts here -->
<div class="container-fluid">
    <div class="row">

        <!-- Blog Entries Column -->
        <div class="col-12 mt-3 left">
            <div class="row">
                {% for post in post_list %}
                <div class="col-md-4">
                    <div class="card mb-4">
                        <div class="card-body">
                            <div class="image-container">
                                {% if "placeholder" in post.featured_image.url %}
                                <img class="card-img-top" src="{% static 'images/default.jpg' %}"
                                    alt="placeholder image">
                                {% else %}
                                <img class="card-img-top" src=" {{ post.featured_image.url }}"
                                    alt="{{ post.title }}">
                                {% endif %}
                                <div class="image-flash">
                                    <p class="author">Author: {{ post.author }}</p>
                                </div>
                            </div>
                            <a href="{% url 'post_detail' post.slug %}" class="post-link">
                                <h2 class="card-title">{{ post.title }}</h2>
                                <p class="card-text">{{ post.excerpt }}</p>
                            </a>

                            <hr>
                            <p class="card-text text-muted h6">{{ post.created_on}}
                            </p>
                        </div>
                    </div>
                </div>
                {% if forloop.counter|divisibleby:3 %}
            </div>
            <div class="row">
                {% endif %}
                {% endfor %}

            </div>
        </div>
    </div>
    {% if is_paginated %}
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PREV </a></li>
            {% endif %}
            {% if page_obj.has_next %}
            <li><a href="?page={{ page_obj.next_page_number }}" class="page-link"> NEXT &raquo;</a></li>
            {% endif %}
        </ul>
    </nav>
    {% endif %}
</div>

<!-- index.html content ends here -->
{% endblock %}

{% block copyright %}
Copyright 2023 Matt Rudge
{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'base.html' %} {% block content %}
{% load static %}
{% load crispy_forms_tags %}

<div class="masthead">
    <div class="container">
        <div class="row g-0">
            <div class="col-md-6 masthead-text">
                <!-- Post title goes in these h1 tags -->
                <h1 class="post-title">{{ post.title }}</h1>
                <!-- Post author goes before the | the post's created date goes after -->
                <p class="post-subtitle">{{ post.author }} | {{ post.created_on }}</p>
            </div>
            <div class="d-none d-md-block col-md-6 masthead-image">
                <img src="{% static 'images/default.jpg' %}" class="scale" alt="placeholder">
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col card mb-4  mt-3 left  top">
            <div class="card-body">
                <!-- The post content goes inside the card-text. -->
                <!-- Use the | safe filter inside the template tags -->
                <article class="card-text">
                    {{ post.content | safe }}
                </article>
            </div>
        </div>
    </div>
    <!-- Displaying count of comments -->
    <div class="row">
        <div class="col-12">
            <strong class="text-secondary">
                <i class="far fa-comments"></i> {{ comment_count }}
            </strong>
        </div>
        <div class="col-12">
            <hr>
        </div>
    </div>
    <!-- Displaying Comments -->
    <div class="row">
        <div class="col-md-8 card mb-4  mt-3 ">
            <h3>Comments:</h3>
            <div class="card-body">
                <!-- We want a for loop inside the empty control tags
          to iterate through each comment in comments -->
                {% for comment in comments %}
                <div class="p-2 comments
          {% if not comment.approved and comment.author == user %}
          faded{% elif not comment.approved %} d-none{% endif %}">
                    <p class="font-weight-bold">
                        {{ comment.author }}
                        <span class="font-weight-normal">
                            {{ comment.created_on }}
                        </span> wrote:
                    </p>
                    <div id="comment{{ comment.id }}">
                        {{ comment.body | linebreaks }}
                    </div>
                    {% if not comment.approved and comment.author == user %}
                    <p class="approval">
                        This comment is awaiting approval
                    </p>
                    {% endif %}
                    {% if user.is_authenticated and comment.author == user %}
                    <button class="btn btn-delete" data-comment_id="{{ comment.id }}">Delete</button>
                    <button class="btn btn-edit" data-comment_id="{{ comment.id }}">Edit</button>
                    {% endif %}
                </div>
                <!-- Our for loop ends here -->
                {% endfor %}
            </div>
        </div>
        <!-- Creating New Comments -->
        <div class="col-md-4 card mb-4 mt-3">
            <div class="card-body">
                {% if user.is_authenticated %}
                <h3>Leave a comment:</h3>
                <p>Posting as: {{ user.username }}</p>
                <form id="commentForm" method="post" style="margin-top: 1.3em;">
                    {{ comment_form | crispy }}
                    {% csrf_token %}
                    <button id="submitButton" type="submit" class="btn btn-signup btn-lg">Submit</button>
                </form>
                {% else %}
                <p>Log in to leave a comment</p>
                {% endif %}
            </div>
        </div>
    </div>
</div>

<!-- Delete confirmation modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel">Delete comment?</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Are you sure you want to delete your comment?
                This action cannot be undone.
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <a id="deleteConfirm" href="#" class="btn
          btn-danger">Delete</a>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

{% block extras %}
<script src="{% static 'js/comments.js' %}"></script>
{% endblock %}